"""Initial schema creation

Revision ID: 3ea4bacba343
Revises: 
Create Date: 2026-02-02 15:34:51.589249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea4bacba343'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batas_wilayah',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('jenis', sa.String(length=50), nullable=False),
    sa.Column('geojson', sa.Text(), nullable=True),
    sa.Column('keterangan', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batas_wilayah', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batas_wilayah_jenis'), ['jenis'], unique=False)

    op.create_table('cctv',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lokasi', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('camera_type', sa.String(length=100), nullable=True),
    sa.Column('stream_url', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kontak',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('instansi', sa.String(length=100), nullable=False),
    sa.Column('nomor_telp', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expiration', sa.DateTime(), nullable=True),
    sa.Column('otp_secret', sa.String(length=6), nullable=True),
    sa.Column('otp_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('reset_token'),
    sa.UniqueConstraint('username')
    )
    op.create_table('counting_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cctv_id', sa.BigInteger(), nullable=False),
    sa.Column('counts_jauh_car', sa.Integer(), nullable=True),
    sa.Column('counts_jauh_motorcycle', sa.Integer(), nullable=True),
    sa.Column('counts_jauh_bus', sa.Integer(), nullable=True),
    sa.Column('counts_jauh_truck', sa.Integer(), nullable=True),
    sa.Column('counts_dekat_car', sa.Integer(), nullable=True),
    sa.Column('counts_dekat_motorcycle', sa.Integer(), nullable=True),
    sa.Column('counts_dekat_bus', sa.Integer(), nullable=True),
    sa.Column('counts_dekat_truck', sa.Integer(), nullable=True),
    sa.Column('grand_total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cctv_id'], ['cctv.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counting_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counting_data_cctv_id'), ['cctv_id'], unique=False)

    op.create_table('crowd_detections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cctv_id', sa.BigInteger(), nullable=False),
    sa.Column('crowd_size', sa.Integer(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cctv_id'], ['cctv.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crowd_detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crowd_detections_cctv_id'), ['cctv_id'], unique=False)

    op.create_table('dispatch',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kontak_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tipe_dispatch', sa.String(length=50), nullable=False),
    sa.Column('instruksi', sa.Text(), nullable=False),
    sa.Column('waktu_kirim', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['kontak_id'], ['kontak.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odol_detections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cctv_id', sa.BigInteger(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('aspect_ratio', sa.Float(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cctv_id'], ['cctv.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odol_detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_odol_detections_cctv_id'), ['cctv_id'], unique=False)

    op.create_table('parking_violations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cctv_id', sa.BigInteger(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('parked_duration_sec', sa.Float(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cctv_id'], ['cctv.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parking_violations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parking_violations_cctv_id'), ['cctv_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_violations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parking_violations_cctv_id'))

    op.drop_table('parking_violations')
    with op.batch_alter_table('odol_detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odol_detections_cctv_id'))

    op.drop_table('odol_detections')
    op.drop_table('dispatch')
    with op.batch_alter_table('crowd_detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crowd_detections_cctv_id'))

    op.drop_table('crowd_detections')
    with op.batch_alter_table('counting_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counting_data_cctv_id'))

    op.drop_table('counting_data')
    op.drop_table('users')
    op.drop_table('kontak')
    op.drop_table('cctv')
    with op.batch_alter_table('batas_wilayah', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batas_wilayah_jenis'))

    op.drop_table('batas_wilayah')
    # ### end Alembic commands ###
